from abc import ABC, abstractmethod

class ExchangeAdapter(ABC):
    name: str
    @abstractmethod
    async def balances(self): ...
    @abstractmethod
    async def positions(self): ...
    @abstractmethod
    async def ticker(self, symbol: str): ...
    @abstractmethod
    async def place_order(self, symbol: str, side: str, quantity: float, order_type: str="market"): ...
